# Generated by Django 3.0.3 on 2020-07-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('current', 'current'), ('completed', 'completed')], default='new', max_length=100),
        ),
    ]
