# Generated by Django 3.0.3 on 2020-07-05 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace_app', '0004_auto_20200705_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
