# Generated by Django 3.0.3 on 2020-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace_app', '0005_auto_20200705_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
