# Generated by Django 3.0.3 on 2020-07-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindspace_app', '0006_activity_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(default=' ', max_length=500),
        ),
    ]
